caringtouch/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("main.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
	path("", views.IndexView, name="index"),
	path("about/", views.AboutView, name="about"),
	path("faq/", views.FaqView, name="faq"),
	path("services/", views.ServicesView, name="services"),
	path("contact/", views.ContactView, name="contact"),
	path("apply/", views.ApplyView, name="apply"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone




class Contact(models.Model):
	name = models.TextField(default="", null=True)
	email = models.CharField(default="",max_length=2000)
	phone = models.CharField(default="",max_length=1000)
	subject =	models.CharField(default="",max_length=1000)
	message = models.TextField(default="",max_length=1130, null=True)	
	pub_date = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		return self.name

class Apply(models.Model):
	name = models.TextField(default="Anonymous")
	cv = models.FileField(upload_to='account_files/profile_photos/', default="default_files/default_face.jpg")
	email = models.CharField(default="",max_length=2000)
	phone = models.CharField(default="",max_length=1000)
	address = models.CharField(default="",max_length=2000)
	start_date = models.CharField(default="",max_length=2000)
	position = models.CharField(default="",max_length=2000)
	qualification = models.TextField(default="",max_length=11130, null=True)
	pub_date = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		return self.name

main/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db.models import Count

from django.core.mail import send_mail
from . models import *
from datetime import datetime
import datetime as dt


def IndexView(request):

	if request.method == "POST":
		pass

	else:
		
		context = {}
		return render(request, "main/index.html", context )


def AboutView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/about.html", context )


def FaqView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/faq.html", context )



def ContactView(request):

	if request.method == "POST":
		email = request.POST.get("email")
		name = request.POST.get("name")
		subject = request.POST.get("subject")
		phone = request.POST.get("phone")
		message = request.POST.get("message")

		contact = Contact.objects.create(
			name=name,  
			email=email, 
			subject=subject, 
			phone=phone, 
			message=message, 
		)
		contact.save()

		messages.warning(request, "Message Delivered!")
		return HttpResponseRedirect(reverse("main:index"))

	else:

		context = {}
		return render(request, "main/contact.html", context )


def ApplyView(request):

	if request.method == "POST":
		email = request.POST.get("email")
		name = request.POST.get("name")
		qualification = request.POST.get("qualification")
		phone = request.POST.get("phone")
		address = request.POST.get("address")
		position = request.POST.get("position")
		start_date = request.POST.get("start_date")
		cv = request.FILES.get("cv")

		application = Apply.objects.create(
			name=name,  
			email=email, 
			qualification=qualification, 
			phone=phone, 
			address=address,
			position=position,
			start_date=start_date,
			cv=cv 
		)
		application.save()

		messages.warning(request, "Application Submitted!")
		return HttpResponseRedirect(reverse("main:index"))

	else:

		context = {}
		return render(request, "main/apply.html", context )


def ServicesView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/services.html", context )

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


        <!-- page-title -->
        <div class="ttm-page-title-row">
            <div class="ttm-page-title-row-inner">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="page-title-heading">
                                <h2 class="title">Contact Us</h2>
                            </div>
                            <div class="breadcrumb-wrapper">
                                <div class="container">
                                    <div class="breadcrumb-wrapper-inner">
                                        <span><a title="Dezily" href="/" class="home">Home</a></span>
                                        <span class="ttm-bread-sep">&nbsp; / &nbsp;</span>
                                        <span>Contact Us</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>                    
        </div><!-- page-title-end -->

        <!--site-main start-->
        <div class="site-main">

        	<!-- map-section -->
        	<section class="ttm-row map-section-2 clearfix">
        		<div class="container">
        			<div class="row">
        				<div class="col-lg-12">
        					<div class="">
        						<div id="google_map" class="google_map style1">
					                <div class="map_container">
					                    <div id="map">
					                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2398.8753129516767!2d-2.9842349!3d53.0405782!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487ac73d559028d7%3A0xdd02064088bf63d!2s3%20Newton%20St%2C%20Wrexham%20LL13%208PE%2C%20UK!5e0!3m2!1sen!2sng!4v1721464144021!5m2!1sen!2sng" width="1170" height="430" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>   


					                    </div>
					                </div>
					            </div>
        					</div>
        				</div>
        			</div>
        			<div class="row">
        				<div class="col-lg-8">
        					<div class="row mt-55 res-1199-mt-0 res-1199-pt-50">
        						<div class="col-lg-12">
        							<h3 class="font-size-26">Get in touch with Senior Helpers</h3>
        						</div>
        					</div>
        					<div class="row mt-15 res-991-mt-0">	
        						
        						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 align-self-center">
        							<div class="res-767-pt-30">
        								<div class="pb-10">
	        								<p>Whether you are looking for care for a loved one or seeking a new career path in the senior care industry, we understand the importance of finding a compassionate and experienced company to partner with.</p>
	        								<p>To speak with a local Caringtouch Healthcare Limited care expert, please complete the form below. We look forward to working with you!.</p>
	        							</div>
	        							<div class="author-info">
	        								<img class="author-sign" src="{% static 'assets/images/author-sign.png' %}" width="216" height="64" alt="author-sign">
	        								<p class="author-position pl-20 pt-10">Co-Founder</p>
	        							</div>
        							</div>
        						</div>
        					</div>
        				</div>
        				<div class="col-lg-4 res-1199-pt-50">
        					<div class="contact-info ttm-bgcolor-white">
	        					<ul class="ttm-list style3">
	        						<li>
	        							<p>Call Anytime</p>
	        							<p><a href="tel:07415211168">07-415-211-168</a></p>
                                        <p><a href="tel:07415211170">07-415-211-170</a></p>
	        						</li>
	        						<li>
	        							<p>Send Email</p>
	        							<a href="mailto:admin@caringtouchhealthcare.co.uk"><span>admin@caringtouchhealth...</span></a>
	        						</li>
	        						<li>
	        							<p>Visit Us</p>
	        							<span>3 Newton Street, Wrexham LL13 8PE, UK</span>
	        						</li>
	        					</ul>
	        					<div class="ttm-horizontal_sep mb-35"></div>
	        					<div class="">
                                    <ul class="social-icons square style1">
                                        <li class="social-facebook"><a href="#" tabindex="0" rel="noopener" aria-label="facebook"><i class="ti ti-facebook"></i></a></li>
                                        <li class="social-twitter"><a href="#" tabindex="0" rel="noopener" aria-label="twitter"><i class="ti ti-twitter-alt"></i></a></li>
                                        <li class="social-linkedin"><a href="#" tabindex="0" rel="noopener" aria-label="linkedin"><i class="ti ti-linkedin"></i></a></li>
                                        <li class="social-pinterest"><a href="#" tabindex="0" rel="noopener" aria-label="pinterest"><i class="ti ti-instagram"></i></a></li>
                                    </ul>
                                </div>
	        				</div>
        				</div>
        			</div>
        		</div>
        	</section>
        	<!-- map-section-end -->

        	<!--consultant-section-->
            <section class="ttm-row consultant-section-3 bg-img2 ttm-bgcolor-dark ttm-textcolor-white ttm-bg ttm-bgimage-yes clearfix">
                <div class="ttm-row-wrapper-bg-layer ttm-bg-layer"></div>
                <div class="container">
                    <div class="row row-title">
                        <div class="col-lg-12 m-auto">
                            <!-- section title -->
                            <div class="section-title title-style-center_text style2">
                                <div class="title-header">
                                    <h3>Heart Care based Solutions</h3>
                                    <h2 class="title">Dedicated to providing <span>comfort and care</span> one smile at a time</h2>
                                </div>
                            </div><!-- section title end -->
                            <div class="consutant-doc-info d-sm-flex justify-content-center align-items-center">
                                <div class="pr-30 res-575-pr-0 text-center">
                                    <a class="ttm-btn ttm-btn-size-md ttm-btn-shape-square ttm-btn-style-border ttm-btn-color-white ttm-icon-btn-right" href="{% url 'main:contact' %}" tabindex="0">Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--consultant-section-->

            <!-- contact-form-section -->
            <section class="ttm-row contact-form-section-2 ttm-bgcolor-grey clearfix">
            	<div class="container">
            		<div class="row">
                        <div class="col-lg-12">
                            <!--section-title -->
                            <div class="section-title">
                                <div class="title-header">
                                    <h3 class="ttm-textcolor-skincolor">Send Message</h3>
                                    <h2 class="title">Get in touch with our experts</h2>
                                </div>
                            </div><!--section-title-end -->
                        </div>
                    </div>
            		<div class="row">
            			<div class="col-lg-12">
            				<div class="mt-15">
        						<form id="contact_form" class="contact_form wrap-form style1 clearfix" method="post" >
                                    {% csrf_token %}
                                    <div class="row ttm-boxes-spacing-20px">
                                        <div class="col-md-6">
                                            <label>
                                                <span class="text-input"><input name="name" type="text"  placeholder="Full Name*" required="required"></span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <label>
                                                <span class="text-input"><input name="email" type="text"  placeholder="Your Email*" required="required"></span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <label>
                                                <span class="text-input"><input name="phone" type="text"  placeholder="Phone Number*" required="required"></span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <label>
                                                <span class="text-input"><input name="subject" type="text" value="" placeholder="Subject*" required="required"></span>
                                            </label>
                                        </div>
                                        <div class="col-md-12">
                                            <label>
                                                <span class="text-input"><textarea name="message" cols="50" rows="5" placeholder="Message" required="required"></textarea></span>
                                            </label>
                                        </div>
                                        <div class="col-lg-12 text-center pt-20">
                                            <button class="submit ttm-btn ttm-btn-size-md ttm-btn-shape-square ttm-btn-color-skincolor" type="submit" tabindex="0">Sund Message</button>
                                        </div>
                                    </div>
                                </form>
        					</div>
            			</div>
            		</div>
            	</div>
            </section>
            <!-- contact-form-section-end -->

        </div>
        <!--site-main end-->

        {% endblock %}

main/templates/main/faq.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

        <!-- page-title -->
        <div class="ttm-page-title-row">
            <div class="ttm-page-title-row-inner">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="page-title-heading">
                                <h2 class="title">FAQ</h2>
                            </div>
                            <div class="breadcrumb-wrapper">
                                <div class="container">
                                    <div class="breadcrumb-wrapper-inner">
                                        <span><a title="Dezily" href="/" class="home">Home</a></span>
                                        <span class="ttm-bread-sep">&nbsp; / &nbsp;</span>
                                        <span>FAQ</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>                    
        </div><!-- page-title-end -->

        <!--site-main start-->
        <div class="site-main">

            <!--faq-section-->
            <section class="ttm-row faq-section bg-layer-equal-height clearfix">
                <div class="container">
                    <!--row-->
                    <div class="row">
                        <div class="col-lg-7 col-md-10 col-sm-12 m-auto">
                            <!--section-title-->
                            <div class="section-title title-style-center_text">
                                <div class="title-header">
                                    <h3>Have any Questions</h3>
                                    <h2 class="title">Recently Asked Questions</h2>
                                </div>
                                <p>Below are some common questions families have asked about Caringtouch Healthcare Limited. If you need more information or would like to speak with one of our helpful team members, please call <a href="tel:07415211168"> 07415211168</a> or <a href="tel:07415211170"> 07415211170</a>.</p>
                            </div><!--section-title end-->
                        </div>
                    </div><!--row end-->
                    <!--row-->
                    <div class="row pt-20">
                        <div class="col-lg-6 col-md-12">
                            <!-- col-img-bg-img-eight-->
                            <div class="col-bg-img-eight ttm-bg ttm-col-bgimage-yes">
                                <div class="ttm-col-wrapper-bg-layer ttm-bg-layer"></div>
                                <div class="layer-content">
                                </div>
                            </div>
                            <!-- col-img-bg-img-eight end-->
                            <img class="ttm-equal-height-image" src="images/bg-image/col-bgimage-8.png" alt="image">
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <div class="res-991-pt-50">
                                <div class="accordion">
                                    <!-- toggle -->
                                    <div class="toggle ttm-toggle_style_classic ttm-toggle-title-bgcolor-grey">
                                        <div class="toggle-title"><a href="about-us.html" class="active">What Does "Aging In Place" Mean?</a></div>
                                        <div class="toggle-content show">
                                            <p>Aging in place refers to a person’s ability to safely grow old in their current residence — whether it is their own home, a family member’s home, or an assisted-living facility.</p>
                                        </div>
                                    </div><!-- toggle end -->
                                    <div class="toggle ttm-toggle_style_classic ttm-toggle-title-bgcolor-grey">
                                        <div class="toggle-title"><a href="about-us.html">What Are The Benefits of In-Home Personal Care?</a></div>
                                        <div class="toggle-content">
                                            <p>In addition to aging in place, a professional caregiver provides many benefits, including:</p>
                                                <ul>
                                                    <li>A customized home care plan that reflects unique needs and requests</li>
                                                    <li>Companionship and social interaction that reduces the risk of isolation and depression</li>
                                                    <li>Flexibility to receive care when needed most</li>
                                                    <li>Lower home care costs when compared to assisted living or nursing home care One-on-one, personalized care</li>
                                                    <li>Peace of mind that your loved one is receiving compassionate care from a trusted professional</li>
                                                    <li>Supervision and assistance that reduces the risk of falls, injuries, and other household accidents</li>
                                                    
                                                </ul>
                                        </div>
                                    </div><!-- toggle end -->
                                    <!-- toggle -->
                                    <div class="toggle ttm-toggle_style_classic ttm-toggle-title-bgcolor-grey">
                                        <div class="toggle-title"><a href="about-us.html">What Services Do Caringtouch Healthcares’ Caregivers Provide?</a></div>
                                        <div class="toggle-content">
                                            <p>Caringtouch Healthcares can provide dedicated companion care and personal care services to assist with everyday activities, so your loved one can preserve their independence while remaining comfortably and safely at home. Home care services include:</p>
                                                <ul>
                                                    <li>Companionship</li>
                                                    <li>Fall prevention</li>
                                                    <li>Grooming, dressing, bathing, and toileting assistance</li>
                                                    <li>Light housekeeping</li>
                                                    <li>Medication reminders</li>
                                                    <li>Meal preparation</li>
                                                    <li>Mobility and transfer assistance</li>
                                                    <li>Running errands</li>
                                                </ul>
                                        </div>
                                    </div><!-- toggle end -->

                                    <div class="toggle ttm-toggle_style_classic ttm-toggle-title-bgcolor-grey">
                                        <div class="toggle-title"><a href="about-us.html">What If I No Longer Need Services?</a></div>
                                        <div class="toggle-content">
                                            <p>If you no longer need services from a Caringtouch Healthcares’ caregiver, you can request a two-week notice to cancel. If you need to decrease the number of hours/days your loved one receives care, you can make permanent schedule changes with a one-week notice.</p>
                                        </div>
                                    </div><!-- toggle end -->

                                    <div class="toggle ttm-toggle_style_classic ttm-toggle-title-bgcolor-grey">
                                        <div class="toggle-title"><a href="about-us.html">Can I Change the Home Care Schedule?</a></div>
                                        <div class="toggle-content">
                                            <p>Yes, you can change or alter the home care schedule. The goal is to make the plan work for your family, not the agency. Although one week’s notice is asked for permanent schedule changes, Caringtouch Healthcare understands unexpected changes are sometimes necessary on short notice. Coordinators will do everything possible to ensure you get the schedule you need to accommodate emergencies.</p>
                                        </div>
                                    </div><!-- toggle end -->

                                    <div class="toggle ttm-toggle_style_classic ttm-toggle-title-bgcolor-grey">
                                        <div class="toggle-title"><a href="about-us.html">What If I Would Like To Select A New Caregiver?</a></div>
                                        <div class="toggle-content">
                                            <p>Caringtouch Healthcare believes successful home care starts with finding the right caregiver. Through the Select Your Caregiver program, a care coordinator will get to know your loved one and provide a personalized recommendation to match them with the right caregiver successfully.</p>

                                            <p>An in-home caregiver can be an adjustment for older adults, and it can take time for your loved one and caregiver to get comfortable with each other. However, if — for any reason at any time — you feel the caregiver isn’t the right match, you can reach out to your coordinator to recommend another caregiver.</p>
                                        </div>
                                    </div><!-- toggle end -->
                                </div>
                            </div> 
                        </div>
                    </div><!-- row end -->
                </div>
            </section><!--faq-section end-->

            <!--connect-section-->
            <section class="ttm-row connect-section bg-img8 ttm-bgcolor-grey ttm-bg ttm-bgimage-yes clearfix">
                <div class="ttm-row-wrapper-bg-layer ttm-bg-layer"></div>
                <div class="container">
                    <!--row-->
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <!-- section title -->
                            <div class="section-title title-style-center_text">
                                <div class="title-header">
                                    <h3>WANT OUR SERVICE?</h3>
                                    <h2 class="title">Get A Solutions For All Types <br> Of Health Services</h2>
                                </div>
                            </div><!-- section title end -->
                            <a class="ttm-btn ttm-btn-size-md ttm-btn-shape-square ttm-btn-style-fill ttm-btn-color-darkgrey" href="{% url 'main:contact' %}" tabindex="0">Contact Us</a>
                        </div>
                    </div><!--row end-->
                </div>
            </section>
            <!--connect-section end-->

        </div><!--site-main end-->

       {% endblock %}